Website = "https://www.facebook.com//"
Forgetpassword = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[3]/a[1]"
Forgetpassword_tab = "identify_email"
Button = "//button[@id='did_submit']"
Incorrect_email__send_key = "henu@gmail.com"
Email_send_key = "mhrethenok@gmail.com"
