Website = "https://www.facebook.com//"
Signin_button = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[5]/a[1]"

# =====================================1========================================
Fn1 = "firstname"
Fn1_send_key = "henu"
Ln1 = "lastname"
Ln1_send_key = "mhret"
Email_1 = "reg_email__"
Email_1_send_key = "mhrethenok@gmail,com"
Email_1_confi = "reg_email_confirmation__"
Email_1_confi_send_key = "mhrethenok@gmail,com"
Password_1 = "reg_passwd__"
Password_1_send_key = "henumhret"
Bd_month1 = "birthday_month"
Bd_month1_option = "//option[contains(text(),'apr')]"
Bd_day1 = "birthday_day"
Bd_day1_option = "//body/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[5]/div[2]/span[1]/span[1]/select[2]/option[3]"
Bd_year1 = "birthday_year"
Bd_year1_option = "//option[contains(text(),'1990')]"
Gender1 = "/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[7]/span[1]/span[2]/input[1]"
Signin = "/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[11]/button[1]"


Fn2_send_key = "123"