from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from Facebook.BaseTest.registration_locators import *
import pytest

def test_registration_1():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    # driver.find_element(By.XPATH, Gender1).click()
    # time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_2():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    # driver.find_element(By.NAME, "birthday_month").click()
    # time.sleep(2)
    # driver.find_element(By.XPATH, "//option[contains(text(),'Jan')]").click()
    # time.sleep(2)
    # driver.find_element(By.NAME, "birthday_day").click()
    # time.sleep(2)
    # driver.find_element(By.XPATH, "//body/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[5]/div[2]/span[1]/span[1]/select[2]/option[3]").click()
    # time.sleep(2)
    # driver.find_element(By.NAME, "birthday_year").click()
    # time.sleep(2)
    # driver.find_element(By.XPATH, "//option[contains(text(),'1990')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_3():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    # coupon = driver.find_element(By.NAME, Password_1)
    # coupon.clear()
    # coupon.send_keys(Password_1_send_key)
    # coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_4():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    # coupon = driver.find_element(By.NAME, Email_1_confi)
    # coupon.clear()
    # coupon.send_keys(Email_1_confi_send_key)
    # time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_5():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    # coupon = driver.find_element(By.NAME, Email_1)
    # coupon.clear()
    # coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_6():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn1_send_key)
    time.sleep(2)
    # coupon = driver.find_element(By.NAME, Ln1)
    # coupon.clear()
    # coupon.send_keys(Ln1_send_key)
    # time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_7():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    # coupon = driver.find_element(By.NAME, Fn1)
    # coupon.clear()
    # coupon.send_keys(Fn1_send_key)
    # time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()


def test_registration_8():
    driver = webdriver.Chrome()
    driver.get(Website)
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin_button).click()
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Fn1)
    coupon.clear()
    coupon.send_keys(Fn2_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Ln1)
    coupon.clear()
    coupon.send_keys(Ln1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1)
    coupon.clear()
    coupon.send_keys(Email_1_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Email_1_confi)
    coupon.clear()
    coupon.send_keys(Email_1_confi_send_key)
    time.sleep(2)
    coupon = driver.find_element(By.NAME, Password_1)
    coupon.clear()
    coupon.send_keys(Password_1_send_key)
    coupon.click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_month1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_month1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_day1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_day1_option).click()
    time.sleep(2)
    driver.find_element(By.NAME, Bd_year1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Bd_year1_option).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Gender1).click()
    time.sleep(2)
    driver.find_element(By.XPATH, Signin).click()
    time.sleep(5)
    driver.close()